---
title: "Facts about Clinicaltrials in United States"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(corrplot)
library(gganimate)
library(plotly)
library(viridis)
```

```{r,include=FALSE}
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}

completion_by_agency = read_csv('completion_by_agency.csv')
nih_ind = completion_by_agency %>% filter(agency_class == "NIH" | agency_class == "Industry")
other_fed = completion_by_agency %>% filter(agency_class != "NIH" & agency_class != "Industry")

nih_ind = nih_ind %>%
  accumulate_by(~completion_year)

other_fed = other_fed %>%
  accumulate_by(~completion_year)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Scatterplot for Coronary Artery Disease

```{r, warning=FALSE}
completion_by_state = read_csv('completion_by_state.csv')
f = completion_by_state %>%
  ggplot(aes(x = location_state, y = total , fill = factor(location_state))) + geom_tile(aes(y = total/2,
 height = total), alpha = 0.7, color = NA) +
  viridis::scale_color_viridis() +
  geom_text(aes(y=total,label = paste("   ",total)), hjust=0 )+
 theme_minimal() +
 theme(
 plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
 axis.ticks.y = element_blank(), 
 axis.text.y = element_blank(), 
 plot.margin = margin(1,1,1,4, "cm")
 ) +
  theme_light() + 
  coord_flip() + 
  scale_y_continuous(labels = scales::comma)+
  theme(legend.position = "none",
        plot.title = element_text(hjust = .5)) +
  labs(
       x = "States",
       y = "Number of Clinicaltrials") +
  transition_states(completion_year,
                    transition_length = 4,
                    state_length = 1) +
  ease_aes('cubic-in-out') +
  labs(title = 'Number of Completed Clinicaltrials in Each States from 1972')
animate(f, fps = 2, width = 800)
```


### add plots here

```{r, warning=FALSE}

```


Column {data-width=500}
-----------------------------------------------------------------------

### Number of Completed Studies Sponsored by NIH and Industry

```{r, warning=FALSE}
nih_ind %>%
      plot_ly(
        x = ~ completion_year,
        y = ~ number_of_clinical_trials,
        frame = ~frame,
        type = 'scatter',
        mode = 'lines',
        color = ~ agency_class,
        text = ~agency_class, hoverinfo = "text") %>%
      layout(yaxis = list(type = "log",title = "Number of Trials"),
             xaxis = list(title = "Completion Year"),
             title = "Number of Completed Studies Sponsored by NIH and Industry") %>%
      add_markers(colors = viridis_pal(option = "D")(2) , frame = ~frame, ids = ~agency_class) %>%
      animation_opts(200, easing = "elastic", transition = 0, redraw = FALSE) %>%
      animation_button(
        x = 1, xanchor = "right", y = 0, yanchor = "bottom") %>%
      animation_slider(hide = T,
        currentvalue = list(prefix = "YEAR ", font = list(color="red")))
```

### Number of Completed Studies Sponsored by U.S. Fed and Others

```{r, warning=FALSE}
other_fed %>%
      plot_ly(
        x = ~ completion_year,
        y = ~ number_of_clinical_trials,
        frame = ~frame,
        type = 'scatter',
        mode = 'lines',
        split = ~agency_class,
        text = ~agency_class, hoverinfo = "text") %>%
      layout(yaxis = list(type = "log",title = "Number of Trials"),
             xaxis = list(title = "Completion Year"),
             title = "Number of Completed Studies Sponsored by U.S. Fed and Others") %>%
      add_markers(color = ~agency_class, frame = ~frame, ids = ~agency_class) %>%
      animation_opts(200, easing = "elastic", transition = 0, redraw = FALSE) %>%
      animation_button(
        x = 1, xanchor = "right", y = 0, yanchor = "bottom"
      ) %>%
      animation_slider(hide = T,
        currentvalue = list(prefix = "YEAR ", font = list(color="red"))
      )
```